title:             Clean Blog
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
url:               "http://int-verg.utkorose.ru"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
permalink: /:title/
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
