title:             Продвижение в интернете
email:             work@utkorose.ru
description:       опыт интернет-вергилия
author:            Start Bootstrap
url:               "http://int-verg.utkorose.ru"

# Social Profiles
twitter_username:  utkorose
github_username:   utkorose
facebook_username: utkorose

# Build settings
markdown:          kramdown
permalink: /:title/
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
