# Site settings
title: "Продвижение в интернете"
email: work@utkorose.ru
description: "Блог о продвижении бизнеса в интернете. Я проведу вас через все круги этого ада."
url: ""

# Build settings
markdown: kramdown
permalink: /:title/
